#pragma once
#define event_battle_role_hit "event_battle_role_hit"
#define event_monster_remove "event_monster_remove"
#define event_role_atk_end "event_role_atk_end"
#define event_boss_drop_item "event_boss_drop_item"
#define event_update_role_hp "event_update_role_hp"
#define event_update_role_lv "event_update_role_lv" 
#define event_battle_role_death "event_battle_role_death"
#define event_battle_role_relive "event_battle_role_relive"
#define event_update_items "event_update_items"
#define event_update_gold "event_update_gold"
#define event_update_equip_part "event_update_equip_part"
#define event_update_equip_bag "event_update_equip_bag"
#define event_update_tasks "event_update_tasks"
#define event_merc_hide "event_merc_hide"
#define event_update_role_power "event_update_role_power"